cargo-features = ["edition"]

[package]
name = "befunge"
version = "0.1.0"
authors = ["Sam Sleight <samuel@sleig.ht>"]

edition = "2018"

[dependencies]
structopt = "0.2.10"
pipeline = { path = "pipeline" }